import React, { useContext } from "react";
import Head from "next/head";
import Link from "next/link";
import { Store } from "../utils/Store";

export default function Layout({ title, children }) {
  const { state } = useContext(Store);
  const { cart } = state;
  return (
    <>
      <Head>
        <title>{title ? title + " - NextMall" : "NextMall"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen justify-between">
        <nav className="flex justify-between items-center bg-slate-200 h-12">
          <Link href="/">
            <a className="text-lg font-bold">NextMall</a>
          </Link>
          <div>
            <Link href="/cart">
              <a className="p-2">
                Cart
                {cart.cartItems.length > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs fond-bold text-white">
                    {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                  </span>
                )}
              </a>
            </Link>
            <Link href="/login">
              <a className="p-2">Login</a>
            </Link>
          </div>
        </nav>
        <main className="container m-auto mt-4 px-4">{children}</main>

        <footer className="flex h-10 bg-red-100 justify-center items-center shadow-inner">
          <p> Copyright &copy; 2022, NextMall</p>
        </footer>
      </div>
    </>
  );
}
