import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { Store } from "../utils/Store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useSession } from "next-auth/react";

export default function Layout({ title, children }) {
  const { state } = useContext(Store);
  const { cart } = state;
  const { status, data: session } = useSession();

  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);
  return (
    <>
      <Head>
        <title>{title ? title + " - NextMall" : "NextMall"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div className="flex flex-col h-scretify-between">
        <nav className="flex justify-between items-center bg-slate-200 h-12">
          <Link href="/">
            <a className="text-lg font-bold">NextMall</a>
          </Link>
          <div>
            <Link href="/cart">
              <a className="p-2">
                Cart
                {cartItemsCount > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs fond-bold text-white">
                    {cartItemsCount}
                  </span>
                )}
              </a>
            </Link>
            {status === "loading" ? (
              "Loading..."
            ) : session?.user ? (
              session.user.name
            ) : (
              <Link href="/login">
                <a className="p-2">Login</a>
              </Link>
            )}
          </div>
        </nav>
        <main className="container m-auto mt-4 px-4">{children}</main>

        <footer className="flex h-10 bg-red-100 justify-center items-center shadow-inner">
          <p> Copyright &copy; 2022, NextMall</p>
        </footer>
      </div>
    </>
  );
}
